apiVersion: v1
kind: Service
metadata:
  name: management-mysql
spec:
  selector:
    app: management-mysql
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-mysql
spec:
  selector:
    matchLabels:
      app: management-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: management-mysql
    spec:
      containers:
        - name: management-mysql
          image: mysql:8
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'root'
            - name: MYSQL_DATABASE
              value: assignments
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb
          configMap:
            name: management-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: management-initdb-config
data:
  initdb.sql: |
    CREATE TABLE assignments
    (
        id          VARCHAR(36) not null,
        title       VARCHAR(50) not null,
        description TEXT        not null,
        deadline    DATETIME    not null,
        status      int         not null,
        PRIMARY KEY (id)
    );
