apiVersion: v1
kind: Pod
metadata:
  name: react-ui
  labels:
    app: react-ui
spec:
  containers:
    - name: react-ui
      image: assignments/react-ui
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    app: react-ui
