apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission
  labels:
    app: submission
spec:
  selector:
    matchLabels:
      app: submission
  replicas: 1
  template:
    metadata:
      labels:
        app: submission
    spec:
      containers:
        - image: assignments/submission
          name: submission
          ports:
            - containerPort: 29999
          args: ["--spring.config.location=application.properties"]
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /app/application.properties
              name: management-config
              subPath: application.properties
      volumes:
        - name: submission-config
          configMap:
            name: submission-config
            items:
              - key: application.properties
                path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: submission
spec:
  ports:
    - port: 29999
      targetPort: 29999
  selector:
    app: submission
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: management-config
data:
  application.properties: |
    spring.datasource.url=jdbc:mysql://submission-mysql:3306/submissions
    spring.datasource.username=root
    spring.datasource.password=root
    server.port=29999
