apiVersion: v1
kind: Service
metadata:
  name: submission-mysql
spec:
  selector:
    app: submission-mysql
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-mysql
spec:
  selector:
    matchLabels:
      app: submission-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: submission-mysql
    spec:
      containers:
        - name: submission-mysql
          image: mysql:8
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'root'
            - name: MYSQL_DATABASE
              value: submissions
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb
          configMap:
            name: submission-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: submission-initdb-config
data:
  initdb.sql: |
    CREATE TABLE submissions
    (
        id         VARCHAR(36) not null,
        code       TEXT        not null,
        assignment VARCHAR(36) NOT NULL,
        user       VARCHAR(36) NOT NULL,
        datetime   DATETIME    NOT NULL,
        PRIMARY KEY (id)
    );
